// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, { Suspense } from "react";
import Providers from "src/app/(features)/(auth)/signin/providers";
import Loading from "./loading";
// import Loading from "./animations";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="font-sans bg-soft-gradient" suppressHydrationWarning={true}>
        <Suspense fallback={<Loading />}>
        <Providers>
          {children}
        </Providers>
        </Suspense>
      </body>
    </html>
  );
}